POC: Remove concurrency blockers, Note::apply_items() handles this now
bundlewrap/bundlewrap pull request #781
Opened 2024-10-28 07:58 UTC by vain

Before polishing this further, I’d like to get some feedback.

We saw in #779 that injecting concurrency blockers can lead to (artificial, unintended) loops. This PR addresses that issue by getting rid of concurrency blockers altogether.

Instead, `Node::apply_items()` now keeps track of which item types are currently running. When asking for the next available item to apply, only non-conflicting items will be considered.

2024-10-28 08:02 UTC, vain commented on bundlewrap/utils/plot.py
> -        if concurrency:
TODO: Remove command line argument `--no-depends-conc` or make it a no-op.

2024-10-30 08:38 UTC, vain commented
I’m relatively certain by now that this works as intended, so I polished it some more.

Testing welcome.

2024-11-01 09:27 UTC, vain commented
Up for discussion with @fkusei and @trehn:

@fkusei mentioned that a `bw verify` does not honor (traditional) concurrency blockers. That’s because `bw verify` does not honor any dependencies whatsoever. I guess that’s fine.

With this new approach, we *could* easily have `bw verify` honor those blockers, though, because they are not implemented as *dependencies* anymore. Should we?

2024-11-04 11:16 UTC, MaZderMind requested changes
Looks very nice & beautiful 👌

2024-11-05 05:48 UTC, vain commented on bundlewrap/itemqueue.py
> +        # Optional sanity check. Remove this mechanism if performance is
I’d be fine with removing the comment about *performance*, but I would want to keep the one about this particular step being *optional*. For future generations.

2024-11-05 05:54 UTC, vain commented on bundlewrap/itemqueue.py
> +            item_types_running.setdefault(i.ITEM_TYPE_NAME, 0)
Okay, done. (Using `defaultdict` effectively *adds* one line, but I don’t think any of this matters, really.)

2024-11-05 07:32 UTC, fkusei approved these changes

2024-11-08 06:21 UTC, vain commented
Ping @MaZderMind. Good to go?

2024-11-08 08:35 UTC, MaZderMind commented
Go go go! ✅

2024-11-12 06:25 UTC, merged